Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -160,33 +160,64 @@ jobs:
           name: app-jar
           path: target/*.jar
           
-  buils_docker_image_and_push:
-    runs-on: self-hosted
-    needs: build_project_and_sonar_scan  
-    steps:
-    - uses: actions/checkout@v4
+  # ============================================================
+# DOCKER BUILD AND PUSH
+# ============================================================
+build_docker_image_and_push:
+  runs-on: self-hosted
+  needs: build_project_and_sonar_scan
+
+  steps:
+
+    - name: Checkout Code
+      uses: actions/checkout@v5
+
     - name: Download JAR artifact
       uses: actions/download-artifact@v4
       with:
         name: app-jar
-        path: app  # this will download JAR to ./app folder
-        
+        path: app
+
+    - name: Verify Docker
+      run: |
+        whoami
+        which docker
+        docker --version
+        docker ps
+
+    - name: Verify Docker Hub Secrets
+      run: |
+        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+          echo "ERROR: DOCKERHUB_USERNAME is EMPTY"
+          exit 1
+        fi
+
+        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+          echo "ERROR: DOCKERHUB_TOKEN is EMPTY"
+          exit 1
+        fi
+
+        echo "Docker Hub credentials are configured"
+
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
-        username: ${{ vars.DOCKERHUB_USERNAME }}
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWD }}
+
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
+
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
-    - name: Build and Push Docker image
+
+    - name: Build and Push Docker Image
       uses: docker/build-push-action@v6
       with:
         context: .
-        push: true
-        tags: adijaiswal/bankapp:latest
         file: ./Dockerfile
+        push: true
+        tags: hariprasad123456/bankapp:latest
 
   # deploy_to_kubernetes:
   #   runs-on: self-hosted
